config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: "users/registrations"
  }, path: "account"

  resources :patients do
    resources :medical_records, controller: "patients/medical_records"
  end
  resources :medical_records, only: %i[index]
  resource :hospital
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "users#index"
end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id          :bigint           not null, primary key
#  born_date   :date
#  family_name :string
#  first_name  :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  doctor_id   :bigint           not null
#  nurse_id    :bigint           not null
#  tenant_id   :bigint           default(3), not null
#
# Indexes
#
#  index_patients_on_doctor_id  (doctor_id)
#  index_patients_on_nurse_id   (nurse_id)
#  index_patients_on_tenant_id  (tenant_id)
#
# Foreign Keys
#
#  fk_rails_...  (tenant_id => hospitals.id)
#
class Patient < ApplicationRecord
  belongs_to :doctor
  belongs_to :nurse
  belongs_to :hospital, foreign_key: :tenant_id
  multi_tenant :tenant
  has_many :medical_records, dependent: :destroy

  def name
    "#{family_name} #{first_name}"
  end
end

app/controllers/patients/medical_records_controller.rb
module Patients
  class MedicalRecordsController < ApplicationController
    before_action :set_medical_record, only: %i[ show edit update destroy ]

    # GET /medical_records or /medical_records.json
    def index
      @medical_records = MedicalRecord.all
    end

    # GET /medical_records/1 or /medical_records/1.json
    def show
    end

    # GET /medical_records/new
    def new
      @patient = Patient.find(params[:patient_id])
      @medical_record = @patient.medical_records.build
    end

    # GET /medical_records/1/edit
    def edit
    end

    # POST /medical_records or /medical_records.json
    def create
      MultiTenant.with(@hospital) do
        @patient = Patient.find(params[:patient_id])
        @medical_record = MedicalRecord.new(medical_record_params)

        @medical_record.patient_id = @patient.id
        @medical_record.writer_id = current_user.id

        if @medical_record.save
          redirect_to patient_medical_record_path(@medical_record.patient.id, @medical_record.id), notice: "Medical record was successfully created."
        else
          render :new, status: :unprocessable_entity
        end
      end
    end

    # PATCH/PUT /medical_records/1 or /medical_records/1.json
    def update
      MultiTenant.with(@hospital) do
        if @medical_record.update(medical_record_params)
          redirect_to patient_medical_record_path(@medical_record.patient.id, @medical_record.id), notice: "Medical record was successfully updated."
        else
          render :edit, status: :unprocessable_entity
        end
      end
    end

    # DELETE /medical_records/1 or /medical_records/1.json
    def destroy
      @medical_record.destroy!

      respond_to do |format|
        format.html { redirect_to medical_records_url, notice: "Medical record was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_medical_record
        @medical_record = MedicalRecord.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def medical_record_params
        params.require(:medical_record).permit(:title, :content)
      end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]
  before_action :build_labels, only: %i[ new create edit update ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all.preload(doctor: [:user, :position], nurse: [:user, :position])
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    MultiTenant.with(@hospital) do
      @patient = Patient.new(patient_params)
      @patient.tenant_id = current_user.tenant_id

      respond_to do |format|
        if @patient.save
          format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
          format.json { render :show, status: :created, location: @patient }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    MultiTenant.with(@hospital) do
      respond_to do |format|
        if @patient.update(patient_params)
          format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
          format.json { render :show, status: :ok, location: @patient }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy!

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:family_name, :first_name, :born_date, :doctor_id, :nurse_id)
    end

    def build_labels
      @doctors = Doctor.joins(:user).preload(:user)
      @nurses = Nurse.joins(:user).preload(:user)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, class: "contents") do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :family_name %>
    <%= form.text_field :family_name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :born_date %>
    <%= form.date_field :born_date, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :doctor %>
    <%= form.collection_select :doctor_id, @doctors, :id, :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :nurse %>
    <%= form.collection_select :nurse_id, @nurses, :id, :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Family name:</strong>
    <%= patient.family_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= patient.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Born date:</strong>
    <%= patient.born_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Doctor:</strong>
    <%= patient.doctor.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Nurse:</strong>
    <%= patient.nurse.name %>
  </p>

</div>

app/views/patients/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing patient</h1>

  <%= render "form", patient: @patient %>

  <%= link_to "Show this patient", @patient, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to patients", patients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/patients/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Patients" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Patients</h1>
    <%= link_to "New patient", new_patient_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="patients" class="min-w-full">
    <% @patients.each do |patient| %>
      <%= render patient %>
      <p>
        <%= link_to "Show this patient", patient, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <%= link_to "New Medical Records", new_patient_medical_record_path(patient), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/patients/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New patient</h1>

  <%= render "form", patient: @patient %>

  <%= link_to "Back to patients", patients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/patients/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @patient %>

    <%= link_to "Edit this patient", edit_patient_path(@patient), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to patients", patients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this patient", @patient, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>