config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: "users/registrations"
  }, path: "account"

  resources :patients do
    resources :medical_records, controller: "patients/medical_records"
  end
  resources :medical_records, only: %i[index]
  resource :hospital
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "users#index"
end

app/models/medical_record.rb
# == Schema Information
#
# Table name: medical_records
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  patient_id :bigint           not null
#  tenant_id  :bigint           not null
#  writer_id  :bigint           not null
#
# Indexes
#
#  index_medical_records_on_patient_id  (patient_id)
#  index_medical_records_on_tenant_id   (tenant_id)
#  index_medical_records_on_writer_id   (writer_id)
#
# Foreign Keys
#
#  fk_rails_...  (patient_id => patients.id)
#  fk_rails_...  (tenant_id => hospitals.id)
#  fk_rails_...  (writer_id => users.id)
#
class MedicalRecord < ApplicationRecord
  belongs_to :patient
  belongs_to :writer, class_name: 'User'
  belongs_to :hospital, foreign_key: :tenant_id
  multi_tenant :tenant

  validates :title, :content, presence: true

  has_rich_text :content

  def writing_date
    I18n.l created_at unless created_at.nil?
  end
end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id          :bigint           not null, primary key
#  born_date   :date
#  family_name :string
#  first_name  :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  doctor_id   :bigint           not null
#  nurse_id    :bigint           not null
#  tenant_id   :bigint           default(3), not null
#
# Indexes
#
#  index_patients_on_doctor_id  (doctor_id)
#  index_patients_on_nurse_id   (nurse_id)
#  index_patients_on_tenant_id  (tenant_id)
#
# Foreign Keys
#
#  fk_rails_...  (tenant_id => hospitals.id)
#
class Patient < ApplicationRecord
  belongs_to :doctor
  belongs_to :nurse
  belongs_to :hospital, foreign_key: :tenant_id
  multi_tenant :tenant
  has_many :medical_records, dependent: :destroy

  def name
    "#{family_name} #{first_name}"
  end
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  # GET /medical_records or /medical_records.json
  def index
    @medical_records = MedicalRecord.preload(:patient).order(created_at: :desc)
  end
end

app/controllers/patients/medical_records_controller.rb
module Patients
  class MedicalRecordsController < ApplicationController
    before_action :set_medical_record, only: %i[ show edit update destroy ]

    # GET /medical_records or /medical_records.json
    def index
      @medical_records = MedicalRecord.all
    end

    # GET /medical_records/1 or /medical_records/1.json
    def show
    end

    # GET /medical_records/new
    def new
      @patient = Patient.find(params[:patient_id])
      @medical_record = @patient.medical_records.build
    end

    # GET /medical_records/1/edit
    def edit
    end

    # POST /medical_records or /medical_records.json
    def create
      MultiTenant.with(@hospital) do
        @patient = Patient.find(params[:patient_id])
        @medical_record = MedicalRecord.new(medical_record_params)

        @medical_record.patient_id = @patient.id
        @medical_record.writer_id = current_user.id

        if @medical_record.save
          redirect_to patient_medical_record_path(@medical_record.patient.id, @medical_record.id), notice: "Medical record was successfully created."
        else
          render :new, status: :unprocessable_entity
        end
      end
    end

    # PATCH/PUT /medical_records/1 or /medical_records/1.json
    def update
      MultiTenant.with(@hospital) do
        if @medical_record.update(medical_record_params)
          redirect_to patient_medical_record_path(@medical_record.patient.id, @medical_record.id), notice: "Medical record was successfully updated."
        else
          render :edit, status: :unprocessable_entity
        end
      end
    end

    # DELETE /medical_records/1 or /medical_records/1.json
    def destroy
      @medical_record.destroy!

      respond_to do |format|
        format.html { redirect_to medical_records_url, notice: "Medical record was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_medical_record
        @medical_record = MedicalRecord.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def medical_record_params
        params.require(:medical_record).permit(:title, :content)
      end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]
  before_action :build_labels, only: %i[ new create edit update ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all.preload(doctor: [:user, :position], nurse: [:user, :position])
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    MultiTenant.with(@hospital) do
      @patient = Patient.new(patient_params)
      @patient.tenant_id = current_user.tenant_id

      respond_to do |format|
        if @patient.save
          format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
          format.json { render :show, status: :created, location: @patient }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    MultiTenant.with(@hospital) do
      respond_to do |format|
        if @patient.update(patient_params)
          format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
          format.json { render :show, status: :ok, location: @patient }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy!

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:family_name, :first_name, :born_date, :doctor_id, :nurse_id)
    end

    def build_labels
      @doctors = Doctor.joins(:user).preload(:user)
      @nurses = Nurse.joins(:user).preload(:user)
    end
end

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/medical_records/_form.html.erb
<%= form_with(model: [medical_record.patient, medical_record]) do |form| %>
  <% if medical_record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(medical_record.errors.count, "error") %> prohibited this medical_record from being saved:</h2>

      <ul>
        <% medical_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

   <div class="mb-3">
    <%= form.label :content, "詳細" %>
    <%= form.rich_text_area :content %>
  </div>
  
  <div class="inline">
    <%= form.submit class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/patients/medical_records/_medical_record.html.erb
<div id="<%= dom_id medical_record %>">
  <p>
    <strong>Patient:</strong>
    <%= medical_record.patient.name %>
  </p>

  <p>
    <strong>Writing date:</strong>
    <%= medical_record.writing_date %>
  </p>

  <p>
    <strong>Writer:</strong>
    <%= medical_record.writer.name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= medical_record.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= medical_record.content %>
  </p>

</div>

app/views/patients/medical_records/edit.html.erb
<h1>Editing medical record</h1>

<%= render "form", medical_record: @medical_record %>

<br>

<div>
  <%= link_to "Show this medical record", patient_medical_record_path(@medical_record.patient.id, @medical_record.id) %> |
  <%= link_to "Back to Patients", patient_medical_record_path(@medical_record.patient) %>
</div>

app/views/patients/medical_records/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Medical records</h1>

<div id="medical_records">
  <% @medical_records.each do |medical_record| %>
    <%= render medical_record %>
    <p>
      <%= link_to "Show this medical record", medical_record %>
    </p>
  <% end %>
</div>

<%= link_to "New medical record", new_medical_record_path %>

app/views/patients/medical_records/new.html.erb
<h1>New medical record</h1>

<%= render "form", medical_record: @medical_record %>

<br>

<div>
  <%= link_to "Back to Patients", patients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/patients/medical_records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @medical_record %>

<div>
  <%= link_to "Edit this medical record", edit_patient_medical_record_path(@medical_record.patient, @medical_record) %> |
  <%= link_to "Back to medical records", medical_records_path %>

  <%= button_to "Destroy this medical record", patient_medical_record_path(@medical_record.patient.id, @medical_record.id), method: :delete %>
</div>